helics: helics::apps::BrokerApp Class Reference
helics::apps::BrokerApp Class Reference
#include <BrokerApp.hpp>
Public Member Functions
BrokerApp ()=default
BrokerApp (int argc, char *argv[])
BrokerApp (core_type ctype, int argc, char *argv[])
BrokerApp (const std::string &argString)
BrokerApp (core_type ctype, const std::string &argString)
BrokerApp (BrokerApp &&other_echo)=default
BrokerApp & operator= (BrokerApp &&brokerApp)=default
~BrokerApp ()
bool isActive () const
void forceTerminate ()
auto * operator-> () const
Detailed Description
class implementing a Broker object. This object is meant to a be a very simple broker executor with a similar interface to the other apps
Constructor & Destructor Documentation
BrokerApp() [1/6]
helics::apps::BrokerApp::BrokerApp () default
default constructor
BrokerApp() [2/6]
helics::apps::BrokerApp::BrokerApp (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
BrokerApp() [3/6]
helics::apps::BrokerApp::BrokerApp (core_type ctype, int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
BrokerApp() [4/6]
helics::apps::BrokerApp::BrokerApp (const std::string & argString) explicit
construct from command line arguments parsed as a single string
Parameters
argString a merged string with all the arguments
References StringToCmdLine::getArgCount(), and StringToCmdLine::getArgV().
BrokerApp() [5/6]
helics::apps::BrokerApp::BrokerApp (core_type ctype, const std::string & argString)
construct from command line arguments parsed as a single string
Parameters
ctype the type of broker to create
argString a merged string with all the arguments
References StringToCmdLine::getArgCount(), and StringToCmdLine::getArgV().
BrokerApp() [6/6]
helics::apps::BrokerApp::BrokerApp (BrokerApp && other_echo) default
move construction
~BrokerApp()
helics::apps::BrokerApp::~BrokerApp ()
the destructor will wait until the broker is finished before returning- unless forceTerminate() is used
References helics::BrokerFactory::cleanUpBrokers().
Member Function Documentation
forceTerminate()
void helics::apps::BrokerApp::forceTerminate ()
forceably disconnect the broker
isActive()
bool helics::apps::BrokerApp::isActive () const
run the Echo federate until the specified time
Parameters
stopTime_input the desired stop timecheck if the Broker is running
operator->()
auto* helics::apps::BrokerApp::operator-> () const inline
overload the -> operator so broker functions can be called if needed
operator=()
BrokerApp& helics::apps::BrokerApp::operator= (BrokerApp && brokerApp) default
move assignment
The documentation for this class was generated from the following files:
BrokerApp.hpp
BrokerApp.cpp