helics: helics::Subscription Class Reference
helics::Subscription Class Reference
#include <Subscriptions.hpp>
Public Member Functions
Subscription (ValueFederate *valueFed, const std::string &key, const std::string &units=std::string())
template<class FedPtr >
Subscription (FedPtr &valueFed, const std::string &key, const std::string &units=std::string())
Subscription (interface_availability required, ValueFederate *valueFed, const std::string &key, const std::string &units=std::string())
template<class FedPtr >
Subscription (interface_availability required, FedPtr &valueFed, const std::string &key, const std::string &units=std::string())
Subscription (ValueFederate *valueFed, const std::string &key, helics_type_t defType, const std::string &units=std::string())
template<class FedPtr >
Subscription (FedPtr &valueFed, const std::string &key, helics_type_t defType, const std::string &units=std::string())
Subscription (interface_availability required, ValueFederate *valueFed, const std::string &key, helics_type_t defType, const std::string &units=std::string())
template<class FedPtr >
Subscription (interface_availability required, FedPtr &valueFed, const std::string &key, helics_type_t defType, const std::string &units=std::string())
Subscription (ValueFederate *valueFed, int subIndex)
virtual bool isUpdated () const override
bool getAndCheckForUpdate ()
template<class X >
std::enable_if_t< helicsType< X >) !=helics_type_t::helicsInvalid, void > registerCallback (std::function< void(const X &, Time)> callback)
template<class X >
void setDefault (X &&val)
void setMinimumChange (double deltaV)
void enableChangeDetection (bool enabled=true)
template<class X >
std::enable_if_t<((helicsType< X >) !=helics_type_t::helicsInvalid)||(isConvertableType< X >)))> getValue (X &out)
template<class X >
std::enable_if_t<((helicsType< X >) !=helics_type_t::helicsInvalid)||(isConvertableType< X >))), X > getValue ()
size_t getRawSize ()
size_t getStringSize ()
size_t getVectorSize ()
Subscription (helics_subscription hsub)
Subscription (const Subscription &subscription)
Subscription & operator= (const Subscription &subscription)
operator helics_subscription () const
helics_subscription baseObject () const
void setDefaultValue (const char *data, int len)
void setDefaultValue (const std::string &str)
void setDefaultValue (int64_t val)
void setDefaultValue (bool val)
void setDefaultValue (double val)
void setDefaultValue (const std::complex< double > &cmplx)
void setDefaultValue (const std::vector< double > &data)
int getRawValue (std::vector< char > &data)
int getValueSize ()
std::string getString ()
void getNamedPoint (std::string &name, double *val)
int64_t getInteger ()
bool getBoolean ()
double getDouble ()
std::complex< double > getComplex ()
int getVector (double *data, int maxlen)
void getVector (std::vector< double > &data)
bool isUpdated () const
helics_time_t getLastUpdateTime () const
std::string getKey () const
std::string getUnits () const
std::string getType () const
void registerCallback (std::function< void(Time)> callback)
Public Member Functions inherited from helics::SubscriptionBase
SubscriptionBase (ValueFederate *valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
template<class FedPtr >
SubscriptionBase (FedPtr &valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
SubscriptionBase (interface_availability required, ValueFederate *valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
template<class FedPtr >
SubscriptionBase (interface_availability required, FedPtr &valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
SubscriptionBase (ValueFederate *valueFed, int subIndex)
SubscriptionBase (SubscriptionBase &&base)=default
SubscriptionBase & operator= (SubscriptionBase &&base)=default
Time getLastUpdate () const
subscription_id_t getID () const
void registerCallback (std::function< void(Time)> callback)
const std::string & getKey () const
const std::string & getName () const
std::string getType () const
const std::string & getUnits () const
Additional Inherited Members
Protected Attributes inherited from helics::SubscriptionBase
ValueFederate * fed = nullptr
reference to the value federate
std::string key_
the name of the subscription
std::string type_
the requested type of the subscription
std::string units_
the defined units of the subscription
subscription_id_t id
the id of the federate
Detailed Description
primary subscription object class
can convert between the helics primary base class types
Constructor & Destructor Documentation
Subscription()
helics::Subscription::Subscription (ValueFederate * valueFed, int subIndex) inline
generate a subscription object from a preexisting subscription
Parameters
valueFed a pointer to the appropriate value Federate
subIndex the index of the subscription
Member Function Documentation
enableChangeDetection()
void helics::Subscription::enableChangeDetection (bool enabled = true) inline
enable change detection
Parameters
enabled (optional) set to false to disable change detection true(default) to enable it
getAndCheckForUpdate()
bool helics::Subscription::getAndCheckForUpdate ()
check if the value has been updated and load the value into buffer
References helics::SubscriptionBase::fed, helics::ValueFederate::getValueRaw(), and helics::SubscriptionBase::isUpdated().
Referenced by getRawSize(), getStringSize(), and getVectorSize().
getLastUpdateTime()
helics_time_t helics::Subscription::getLastUpdateTime () const inline
Get the last time a subscription was updated
References helicsSubscriptionLastUpdateTime().
getRawSize()
size_t helics::Subscription::getRawSize ()
get the size of the raw data
References helics::SubscriptionBase::fed, getAndCheckForUpdate(), and helics::ValueFederate::getValueRaw().
getRawValue()
int helics::Subscription::getRawValue (std::vector< char > & data) inline
Methods to get subscription values
References helicsSubscriptionGetRawValue(), and helicsSubscriptionGetValueSize().
getStringSize()
size_t helics::Subscription::getStringSize ()
get the size of the data if it were a string
References getAndCheckForUpdate().
getValue() [1/2]
template<class X > std::enable_if_t<((helicsType<X>) != helics_type_t::helicsInvalid) || (isConvertableType<X>)))> helics::Subscription::getValue (X & out) inline
get the latest value for the subscription
Parameters
[out] out the location to store the value
getValue() [2/2]
template<class X > std::enable_if_t<((helicsType<X>) != helics_type_t::helicsInvalid) || (isConvertableType<X>))), X> helics::Subscription::getValue () inline
get the most recent value
Returns
the value
getVectorSize()
size_t helics::Subscription::getVectorSize ()
get the number of elements in the data if it were a vector
References getAndCheckForUpdate().
isUpdated() [1/2]
bool helics::Subscription::isUpdated () const inline virtual
Check if a subscription is updated
Reimplemented from helics::SubscriptionBase.
References helicsSubscriptionIsUpdated().
isUpdated() [2/2]
bool helics::Subscription::isUpdated () const override virtual
check if the value has been updated
Reimplemented from helics::SubscriptionBase.
References helics::SubscriptionBase::isUpdated().
registerCallback() [1/2]
void helics::SubscriptionBase::registerCallback inline
register a callback for an update notification
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(Time time) time is the time the value was updated This callback is a notification callback and doesn't return the value
registerCallback() [2/2]
template<class X > std::enable_if_t<helicsType<X>) != helics_type_t::helicsInvalid, void> helics::Subscription::registerCallback (std::function< void(const X &, Time)> callback) inline
register a callback for the update
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(X val, Time time) val is the new value and time is the time the value was updated
References helics::SubscriptionBase::fed, and helics::ValueFederate::registerSubscriptionNotificationCallback().
setDefault()
template<class X > void helics::Subscription::setDefault (X && val) inline
set the default value to use before any update has been published
References helics::make_valid().
setDefaultValue()
void helics::Subscription::setDefaultValue (const char * data, int len) inline
Methods to set default values for subscriptions
References helicsSubscriptionSetDefaultRaw().
setMinimumChange()
void helics::Subscription::setMinimumChange (double deltaV) inline
set the minimum delta for change detection
Parameters
detltaV a double with the change in a value in order to register a different value
The documentation for this class was generated from the following files:
Subscriptions.hpp
Subscription.hpp
Subscriptions.cpp