helics: GetValue functions
GetValue functions
Functions
HELICS_EXPORT int helicsSubscriptionGetValueSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetRawValue (helics_subscription sub, void *data, int maxlen, int *actualLength)
HELICS_EXPORT int helicsSubscriptionGetStringSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetString (helics_subscription sub, char *outputString, int maxStringlen, int *actualLength)
HELICS_EXPORT helics_status helicsSubscriptionGetInteger (helics_subscription sub, int64_t *val)
HELICS_EXPORT helics_status helicsSubscriptionGetBoolean (helics_subscription sub, helics_bool_t *val)
HELICS_EXPORT helics_status helicsSubscriptionGetDouble (helics_subscription sub, double *val)
HELICS_EXPORT helics_status helicsSubscriptionGetComplex (helics_subscription sub, double *real, double *imag)
HELICS_EXPORT int helicsSubscriptionGetVectorSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetVector (helics_subscription sub, double data[], int maxlen, int *actualSize)
HELICS_EXPORT helics_status helicsSubscriptionGetNamedPoint (helics_subscription sub, char *outputString, int maxStringlen, int *actualLength, double *val)
Detailed Description
data can be returned in number of formats, for instance if data is published as a double it can be returned as a string and vice versa, not all translations make that much sense but they do work.
Function Documentation
helicsSubscriptionGetBoolean()
HELICS_EXPORT helics_status helicsSubscriptionGetBoolean (helics_subscription sub, helics_bool_t * val)
get a boolean value from a subscription
Parameters
sub the subscription to get the data for
[out] val memory location to place the value
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, and helics_invalid_object.
helicsSubscriptionGetComplex()
HELICS_EXPORT helics_status helicsSubscriptionGetComplex (helics_subscription sub, double * real, double * imag)
get a pair of double forming a complex number from a subscriptions
Parameters
sub the subscription to get the data for
[out] real memory location to place the real part of a value
[out] imag memory location to place the imaginary part of a value
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, helics_invalid_object, and helics_ok.
helicsSubscriptionGetDouble()
HELICS_EXPORT helics_status helicsSubscriptionGetDouble (helics_subscription sub, double * val)
get a double value from a subscription
Parameters
sub the subscription to get the data for
[out] val memory location to place the value
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, helics_invalid_object, and helics_ok.
helicsSubscriptionGetInteger()
HELICS_EXPORT helics_status helicsSubscriptionGetInteger (helics_subscription sub, int64_t * val)
get an integer value from a subscription
Parameters
sub the subscription to get the data for
[out] val memory location to place the value
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, helics_invalid_object, and helics_ok.
helicsSubscriptionGetNamedPoint()
HELICS_EXPORT helics_status helicsSubscriptionGetNamedPoint (helics_subscription sub, char * outputString, int maxStringlen, int * actualLength, double * val)
get a named point from a subscription
Parameters
sub the subscription to get the result for
[out] str storage for copying a null terminated string
maxlen the maximum size of information that str can hold
[out] the actual length of the string
[out] val the double value for the named point
References helics_invalid_argument, helics_invalid_object, helics_ok, and helics_warning.
helicsSubscriptionGetRawValue()
HELICS_EXPORT helics_status helicsSubscriptionGetRawValue (helics_subscription sub, void * data, int maxlen, int * actualLength)
get the raw data for the latest value of a subscription
Parameters
sub the subscription to get the data for
[out] data the memory location of the data
maxlen the maximum size of information that data can hold
[out] actualLength the actual length of data copied to data
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, helics_invalid_object, helics_ok, and helics_warning.
Referenced by helics::Subscription::getRawValue(), and helicsSubscriptionGetString().
helicsSubscriptionGetString()
HELICS_EXPORT helics_status helicsSubscriptionGetString (helics_subscription sub, char * outputString, int maxStringlen, int * actualLength)
get a string value from a subscription
Parameters
sub the subscription to get the data for
[out] str storage for copying a null terminated string
maxlen the maximum size of information that str can hold
[out] the actual length of the string
Returns
a helics_status value, helics_ok if everything went fine
References helics_invalid_argument, helics_invalid_object, helics_warning, and helicsSubscriptionGetRawValue().
helicsSubscriptionGetStringSize()
HELICS_EXPORT int helicsSubscriptionGetStringSize (helics_subscription sub)
get the size of a value for subscription assuming return as a string
Returns
the size of the string
helicsSubscriptionGetValueSize()
HELICS_EXPORT int helicsSubscriptionGetValueSize (helics_subscription sub)
get the size of the raw value for subscription
Returns
the size of the raw data/string in bytes
References helics_invalid_object.
Referenced by helics::Subscription::getRawValue().
helicsSubscriptionGetVector()
HELICS_EXPORT helics_status helicsSubscriptionGetVector (helics_subscription sub, double data[], int maxlen, int * actualSize)
get a vector from a subscription
Parameters
sub the subscription to get the result for
[out] data the location to store the data
maxlen the maximum size of the vector
[out] actualSize pointer to variable to store the actual size
References helics_invalid_argument, helics_invalid_object, helics_ok, and helics_warning.
helicsSubscriptionGetVectorSize()
HELICS_EXPORT int helicsSubscriptionGetVectorSize (helics_subscription sub)
get the size of a value for subscription assuming return as an array of doubles
Returns
the number of double in a return vector