helics: helics.h File Reference
helics.h File Reference
common functions for the HELICS C api
#include "api-data.h"
#include <stdlib.h>
#include "helics_export.h"
Functions
HELICS_EXPORT const char * helicsGetVersion ()
HELICS_EXPORT helics_bool_t helicsIsCoreTypeAvailable (const char *type)
HELICS_EXPORT helics_core helicsCreateCore (const char *type, const char *name, const char *initString)
HELICS_EXPORT helics_core helicsCreateCoreFromArgs (const char *type, const char *name, int argc, const char *const *argv)
HELICS_EXPORT helics_core helicsCoreClone (helics_core core)
HELICS_EXPORT helics_broker helicsCreateBroker (const char *type, const char *name, const char *initString)
HELICS_EXPORT helics_broker helicsCreateBrokerFromArgs (const char *type, const char *name, int argc, const char *const *argv)
HELICS_EXPORT helics_broker helicsBrokerClone (helics_broker broker)
HELICS_EXPORT int helicsBrokerIsConnected (helics_broker broker)
HELICS_EXPORT int helicsCoreIsConnected (helics_core core)
HELICS_EXPORT helics_status helicsBrokerGetIdentifier (helics_broker broker, char *identifier, int maxlen)
HELICS_EXPORT helics_status helicsCoreGetIdentifier (helics_core core, char *identifier, int maxlen)
HELICS_EXPORT helics_status helicsBrokerGetAddress (helics_broker broker, char *address, int maxlen)
HELICS_EXPORT helics_status helicsCoreSetReadyToInit (helics_core core)
HELICS_EXPORT helics_status helicsCoreDisconnect (helics_core core)
HELICS_EXPORT helics_federate helicsGetFederateByName (const char *fedName)
HELICS_EXPORT helics_status helicsBrokerDisconnect (helics_broker broker)
HELICS_EXPORT void helicsCoreFree (helics_core core)
HELICS_EXPORT void helicsBrokerFree (helics_broker broker)
HELICS_EXPORT helics_federate helicsCreateValueFederate (const helics_federate_info_t fi)
HELICS_EXPORT helics_federate helicsCreateValueFederateFromJson (const char *json)
HELICS_EXPORT helics_federate helicsCreateMessageFederate (const helics_federate_info_t fi)
HELICS_EXPORT helics_federate helicsCreateMessageFederateFromJson (const char *json)
HELICS_EXPORT helics_federate helicsCreateCombinationFederate (const helics_federate_info_t fi)
HELICS_EXPORT helics_federate helicsCreateCombinationFederateFromJson (const char *json)
HELICS_EXPORT helics_federate helicsFederateClone (helics_federate fed)
HELICS_EXPORT helics_federate_info_t helicsFederateInfoCreate ()
HELICS_EXPORT helics_status helicsFederateInfoLoadFromArgs (helics_federate_info_t fi, int argc, const char *const *argv)
HELICS_EXPORT void helicsFederateInfoFree (helics_federate_info_t fi)
HELICS_EXPORT helics_status helicsFederateInfoSetFederateName (helics_federate_info_t fi, const char *name)
HELICS_EXPORT helics_status helicsFederateInfoSetCoreName (helics_federate_info_t fi, const char *corename)
HELICS_EXPORT helics_status helicsFederateInfoSetCoreInitString (helics_federate_info_t fi, const char *coreInit)
HELICS_EXPORT helics_status helicsFederateInfoSetCoreTypeFromString (helics_federate_info_t fi, const char *coretype)
HELICS_EXPORT helics_status helicsFederateInfoSetCoreType (helics_federate_info_t fi, int coretype)
HELICS_EXPORT helics_status helicsFederateInfoSetFlag (helics_federate_info_t fi, int flag, helics_bool_t value)
HELICS_EXPORT helics_status helicsFederateInfoSetSeparator (helics_federate_info_t fi, char separator)
HELICS_EXPORT helics_status helicsFederateInfoSetOutputDelay (helics_federate_info_t fi, helics_time_t outputDelay)
HELICS_EXPORT helics_status helicsFederateInfoSetTimeDelta (helics_federate_info_t fi, helics_time_t timeDelta)
HELICS_EXPORT helics_status helicsFederateInfoSetInputDelay (helics_federate_info_t fi, helics_time_t inputDelay)
HELICS_EXPORT helics_status helicsFederateInfoSetTimeOffset (helics_federate_info_t fi, helics_time_t timeOffset)
HELICS_EXPORT helics_status helicsFederateInfoSetPeriod (helics_federate_info_t fi, helics_time_t period)
HELICS_EXPORT helics_status helicsFederateInfoSetMaxIterations (helics_federate_info_t fi, int maxIterations)
HELICS_EXPORT helics_status helicsFederateInfoSetLoggingLevel (helics_federate_info_t fi, int logLevel)
HELICS_EXPORT helics_status helicsFederateFinalize (helics_federate fed)
HELICS_EXPORT void helicsFederateFree (helics_federate fed)
HELICS_EXPORT void helicsCloseLibrary ()
HELICS_EXPORT helics_status helicsFederateEnterInitializationMode (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterInitializationModeAsync (helics_federate fed)
HELICS_EXPORT helics_bool_t helicsFederateIsAsyncOperationCompleted (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterInitializationModeComplete (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterExecutionMode (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeAsync (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeComplete (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterative (helics_federate fed, helics_iteration_request iterate, helics_iteration_status *outIterate)
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterativeAsync (helics_federate fed, helics_iteration_request iterate)
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterativeComplete (helics_federate fed, helics_iteration_status *outIterate)
HELICS_EXPORT helics_status helicsFederateGetState (helics_federate fed, federate_state *state)
HELICS_EXPORT helics_core helicsFederateGetCoreObject (helics_federate fed)
HELICS_EXPORT helics_status helicsFederateRequestTime (helics_federate fed, helics_time_t requestTime, helics_time_t *timeOut)
HELICS_EXPORT helics_status helicsFederateRequestTimeIterative (helics_federate fed, helics_time_t requestTime, helics_iteration_request iterate, helics_time_t *timeOut, helics_iteration_status *outIterate)
HELICS_EXPORT helics_status helicsFederateRequestTimeAsync (helics_federate fed, helics_time_t requestTime)
HELICS_EXPORT helics_status helicsFederateRequestTimeComplete (helics_federate fed, helics_time_t *timeOut)
HELICS_EXPORT helics_status helicsFederateRequestTimeIterativeAsync (helics_federate fed, helics_time_t requestTime, helics_iteration_request iterate)
HELICS_EXPORT helics_status helicsFederateRequestTimeIterativeComplete (helics_federate fed, helics_time_t *timeOut, helics_iteration_status *outIterate)
HELICS_EXPORT helics_status helicsFederateGetName (helics_federate fed, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsFederateSetTimeDelta (helics_federate fed, helics_time_t time)
HELICS_EXPORT helics_status helicsFederateSetOutputDelay (helics_federate fed, helics_time_t outputDelay)
HELICS_EXPORT helics_status helicsFederateSetInputDelay (helics_federate fed, helics_time_t inputDelay)
HELICS_EXPORT helics_status helicsFederateSetPeriod (helics_federate fed, helics_time_t period, helics_time_t offset)
HELICS_EXPORT helics_status helicsFederateSetFlag (helics_federate fed, int flag, helics_bool_t flagValue)
HELICS_EXPORT helics_status helicsFederateSetSeparator (helics_federate fed, char separator)
HELICS_EXPORT helics_status helicsFederateSetLoggingLevel (helics_federate fed, int loggingLevel)
HELICS_EXPORT helics_status helicsFederateSetMaxIterations (helics_federate fi, int maxIterations)
HELICS_EXPORT helics_status helicsFederateGetCurrentTime (helics_federate fed, helics_time_t *time)
HELICS_EXPORT helics_query helicsCreateQuery (const char *target, const char *query)
HELICS_EXPORT const char * helicsQueryExecute (helics_query query, helics_federate fed)
HELICS_EXPORT const char * helicsQueryCoreExecute (helics_query query, helics_core core)
HELICS_EXPORT const char * helicsQueryBrokerExecute (helics_query query, helics_broker broker)
HELICS_EXPORT helics_status helicsQueryExecuteAsync (helics_query query, helics_federate fed)
HELICS_EXPORT const char * helicsQueryExecuteComplete (helics_query query)
HELICS_EXPORT helics_bool_t helicsQueryIsCompleted (helics_query query)
HELICS_EXPORT void helicsQueryFree (helics_query)
HELICS_EXPORT void helicsCleanupHelicsLibrary ()
Detailed Description
common functions for the HELICS C api
Function Documentation
helicsBrokerClone()
HELICS_EXPORT helics_broker helicsBrokerClone (helics_broker broker)
create a new reference to an existing broker
this will create a new broker object that references the existing broker it must be freed as well
Parameters
broker an existing helics_broker
Returns
a new reference to the same broker
helicsBrokerDisconnect()
HELICS_EXPORT helics_status helicsBrokerDisconnect (helics_broker broker)
disconnect a broker
Parameters
broker the broker to disconnect
Returns
a helics_status enumeration indicating any error condition
References helics_error, helics_invalid_object, and helics_ok.
helicsBrokerFree()
HELICS_EXPORT void helicsBrokerFree (helics_broker broker)
release the memory associated with a broker
References helics::BrokerFactory::cleanUpBrokers().
helicsBrokerGetAddress()
HELICS_EXPORT helics_status helicsBrokerGetAddress (helics_broker broker, char * address, int maxlen)
get the network address associated with a broker
Parameters
broker the broker to query
[out] identifier storage space to place the identifier string
maxlen the maximum space available in identifier
Returns
a helics_status enumeration indicating any error condition
References helics_invalid_object, and helics_ok.
helicsBrokerGetIdentifier()
HELICS_EXPORT helics_status helicsBrokerGetIdentifier (helics_broker broker, char * identifier, int maxlen)
get an identifier for the broker
Parameters
broker the broker to query
[out] identifier storage space to place the identifier string
maxlen the maximum space available in identifier
Returns
a helics_status enumeration indicating any error condition
References helics_invalid_object, and helics_ok.
helicsBrokerIsConnected()
HELICS_EXPORT int helicsBrokerIsConnected (helics_broker broker)
check if a broker is connected a connected broker implies is attached to cores or cores could reach out to communicate return 0 if not connected , something else if it is connected
helicsCleanupHelicsLibrary()
HELICS_EXPORT void helicsCleanupHelicsLibrary ()
function to do some housekeeping work
this runs some cleanup routines and tries to close out any residual thread that haven't been shutdown yet
References helics::cleanupHelicsLibrary().
helicsCloseLibrary()
HELICS_EXPORT void helicsCloseLibrary ()
call when done using the helics library, this function will ensure the threads are closed properly if possible this should be the last call before exiting,
References helics::BrokerFactory::cleanUpBrokers(), helics::CoreFactory::cleanUpCores(), helics::LoggerManager::closeLogger(), and zmqContextManager::setContextToLeakOnDelete().
helicsCoreClone()
HELICS_EXPORT helics_core helicsCoreClone (helics_core core)
create a new reference to an existing broker
this will create a new broker object that references the existing broker it must be freed as well
Parameters
broker an existing helics_broker
Returns
a new reference to the same broker
helicsCoreDisconnect()
HELICS_EXPORT helics_status helicsCoreDisconnect (helics_core core)
get an identifier for the core
Parameters
core the core to query
[out] identifier storage space to place the identifier string
maxlen the maximum space available in identifier
Returns
a helics_status enumeration indicating any error condition
References helics_invalid_object, and helics_ok.
helicsCoreFree()
HELICS_EXPORT void helicsCoreFree (helics_core core)
release the memory associated with a core
References helics::CoreFactory::cleanUpCores().
helicsCoreGetIdentifier()
HELICS_EXPORT helics_status helicsCoreGetIdentifier (helics_core core, char * identifier, int maxlen)
get an identifier for the core
Parameters
core the core to query
[out] identifier storage space to place the identifier string
maxlen the maximum space available in identifier
Returns
a helics_status enumeration indicating any error condition
References helics_invalid_object, and helics_ok.
helicsCoreIsConnected()
HELICS_EXPORT int helicsCoreIsConnected (helics_core core)
check if a core is connected a connected core implies is attached to federate or federates could be attached to it return 0 if not connected , something else if it is connected
helicsCoreSetReadyToInit()
HELICS_EXPORT helics_status helicsCoreSetReadyToInit (helics_core core)
set the core to ready to init
this function is used for cores that have filters but no federates so there needs to be a direct signal to the core to trigger the federation initialization
References helics_invalid_object, and helics_ok.
helicsCreateBroker()
HELICS_EXPORT helics_broker helicsCreateBroker (const char * type, const char * name, const char * initString)
create a broker object
Parameters
type the type of the broker to create
name the name of the broker , may be a nullptr or empty string to have a name automatically assigned
initString an initialization string to send to the core-the format is similar to command line arguments typical options include a broker address –broker="XSSAF" if this is a subbroker or the number of federates or the address
Returns
a helics_core object
References helics::coreTypeFromString(), helics::BrokerFactory::create(), and helics::DEFAULT.
helicsCreateBrokerFromArgs()
HELICS_EXPORT helics_broker helicsCreateBrokerFromArgs (const char * type, const char * name, int argc, const char *const * argv)
create a core object by passing command line arguments
Parameters
type the type of the core to create
name the name of the core , may be a nullptr or empty string to have a name automatically assigned
argc the number of arguments
argv the string values from a command line
Returns
a helics_core object
References helics::coreTypeFromString(), helics::BrokerFactory::create(), and helics::DEFAULT.
helicsCreateCombinationFederate()
HELICS_EXPORT helics_federate helicsCreateCombinationFederate (const helics_federate_info_t fi)
create a combination federate from a federate info object
combination federates are both value federates and message federates, objects can be used in all functions that take a helics_federate, helics_message_federate or helics_federate object as an argument
Parameters
fi the federate info object that contains details on the federate
Returns
an opaque value federate object nullptr if the object creation failed
helicsCreateCombinationFederateFromJson()
HELICS_EXPORT helics_federate helicsCreateCombinationFederateFromJson (const char * json)
create a combination federate from a JSON file or JSON string
combination federates are both value federates and message federates, objects can be used in all functions that take a helics_federate, helics_message_federate or helics_federate object as an argument
Parameters
JSON a JSON file or a JSON string that contains setup and configuration information
Returns
an opaque combination federate object
helicsCreateCore()
HELICS_EXPORT helics_core helicsCreateCore (const char * type, const char * name, const char * initString)
create a core object
Parameters
type the type of the core to create
name the name of the core , may be a nullptr or empty string to have a name automatically assigned
initString an initialization string to send to the core-the format is similar to command line arguments typical options include a broker address –broker="XSSAF" or the number of federates or the address
Returns
a helics_core object
References helics::coreTypeFromString(), helics::DEFAULT, and helics::CoreFactory::FindOrCreate().
helicsCreateCoreFromArgs()
HELICS_EXPORT helics_core helicsCreateCoreFromArgs (const char * type, const char * name, int argc, const char *const * argv)
create a core object by passing command line arguments
Parameters
type the type of the core to create
name the name of the core , may be a nullptr or empty string to have a name automatically assigned
argc the number of arguments
argv the string values from a command line
Returns
a helics_core object
References helics::coreTypeFromString(), helics::DEFAULT, and helics::CoreFactory::FindOrCreate().
helicsCreateMessageFederate()
HELICS_EXPORT helics_federate helicsCreateMessageFederate (const helics_federate_info_t fi)
create a message federate from a federate info object
helics_message_federate objects can be used in all functions that take a helics_message_federate or helics_federate object as an argument
Parameters
fi the federate info object that contains details on the federate
Returns
an opaque message federate object
helicsCreateMessageFederateFromJson()
HELICS_EXPORT helics_federate helicsCreateMessageFederateFromJson (const char * json)
create a message federate from a JSON file or JSON string
helics_message_federate objects can be used in all functions that take a helics_message_federate or helics_federate object as an argument
Parameters
JSON a JSON file or a JSON string that contains setup and configuration information
Returns
an opaque message federate object
helicsCreateQuery()
HELICS_EXPORT helics_query helicsCreateQuery (const char * target, const char * query)
create a query object
a query object consists of a target and query string
References helics::queryObject::query.
Referenced by helics::Federate::query().
helicsCreateValueFederate()
HELICS_EXPORT helics_federate helicsCreateValueFederate (const helics_federate_info_t fi)
create a value federate from a federate info object
helics_federate objects can be used in all functions that take a helics_federate or helics_federate object as an argument
Parameters
fi the federate info object that contains details on the federate
Returns
an opaque value federate object
helicsCreateValueFederateFromJson()
HELICS_EXPORT helics_federate helicsCreateValueFederateFromJson (const char * json)
create a value federate from a JSON file or JSON string
helics_federate objects can be used in all functions that take a helics_federate or helics_federate object as an argument
Parameters
JSON a JSON file or a JSON string that contains setup and configuration information
Returns
an opaque value federate object
helicsFederateClone()
HELICS_EXPORT helics_federate helicsFederateClone (helics_federate fed)
create a new reference to an existing federate
this will create a new helics_federate object that references the existing federate it must be freed as well
Parameters
fed an existing helics_federate
Returns
a new reference to the same federate
Referenced by helicsGetFederateByName().
helicsFederateEnterExecutionMode()
HELICS_EXPORT helics_status helicsFederateEnterExecutionMode (helics_federate fed)
request that the federate enter the Execution mode
this call is blocking until granted entry by the core object for an asynchronous alternative call /ref helicsFederateEnterExecutionModeAsync on return from this call the federate will be at time 0
Parameters
fed a federate to change modes
Returns
a helics_status enumeration helics_error if something went wrong helicsInvalidReference if fed is invalid
References helics_invalid_object, and helics_ok.
helicsFederateEnterExecutionModeAsync()
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeAsync (helics_federate fed)
request that the federate enter the Execution mode
this call is non-blocking and will return immediately call /ref helicsFederateEnterExecutionModeComplete to finish the call sequence /ref
References helics_invalid_object, and helics_ok.
helicsFederateEnterExecutionModeComplete()
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeComplete (helics_federate fed)
complete the call to /ref EnterExecutionModeAsync
Parameters
fed the federate object to complete the call
References helics_invalid_object, and helics_ok.
helicsFederateEnterExecutionModeIterative()
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterative (helics_federate fed, helics_iteration_request iterate, helics_iteration_status * outIterate)
request an iterative time
this call allows for finer grain control of the iterative process then /ref helicsFederateRequestTime it takes a time and and iteration request and return a time and iteration status
Parameters
fed the federate to make the request of
iterate the requested iteration mode
[out] outIterate the iteration specification of the result
Returns
a helics_status object with a return code of the result
References helics_invalid_object, and helics_ok.
helicsFederateEnterExecutionModeIterativeAsync()
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterativeAsync (helics_federate fed, helics_iteration_request iterate)
request an iterative entry to the execution mode
this call allows for finer grain control of the iterative process then /ref helicsFederateRequestTime it takes a time and and iteration request and return a time and iteration status
Parameters
fed the federate to make the request of
iterate the requested iteration mode
Returns
a helics_status object with a return code of the result
References helics_invalid_object, and helics_ok.
helicsFederateEnterExecutionModeIterativeComplete()
HELICS_EXPORT helics_status helicsFederateEnterExecutionModeIterativeComplete (helics_federate fed, helics_iteration_status * outIterate)
complete the asynchronous iterative call into ExecutionModel
Parameters
fed the federate to make the request of
[out] outIterate the iteration specification of the result
Returns
a helics_status object with a return code of the result helics_ok if there were no issues
References helics_invalid_object, and helics_ok.
helicsFederateEnterInitializationMode()
HELICS_EXPORT helics_status helicsFederateEnterInitializationMode (helics_federate fed)
enter the initialization state of a federate
the initialization state allows initial values to be set and received if the iteration is requested on entry to the execution state This is a blocking call and will block until the core allows it to proceed
References helics_invalid_object, and helics_ok.
helicsFederateEnterInitializationModeAsync()
HELICS_EXPORT helics_status helicsFederateEnterInitializationModeAsync (helics_federate fed)
non blocking alternative to the function helicsFederateEnterInitializationModeFinalize must be called to finish the operation
References helics_invalid_object, and helics_ok.
helicsFederateEnterInitializationModeComplete()
HELICS_EXPORT helics_status helicsFederateEnterInitializationModeComplete (helics_federate fed)
finalize the entry to initialize mode that was initiated with
References helics_invalid_object, and helics_ok.
helicsFederateFinalize()
HELICS_EXPORT helics_status helicsFederateFinalize (helics_federate fed)
finalize the federate this halts all communication in the federate and disconnects it from the core
References helics_invalid_object, and helics_ok.
helicsFederateFree()
HELICS_EXPORT void helicsFederateFree (helics_federate fed)
release the memory associated withe a federate
References helics::CoreFactory::cleanUpCores().
helicsFederateGetCoreObject()
HELICS_EXPORT helics_core helicsFederateGetCoreObject (helics_federate fed)
get the core object associated with a federate
Parameters
fed a federate object
Returns
a core object, nullptr if invalid
helicsFederateGetCurrentTime()
HELICS_EXPORT helics_status helicsFederateGetCurrentTime (helics_federate fed, helics_time_t * time)
get the current time of the federate
Parameters
fed the federate object to query
[out] time storage location for the time variable
Returns
helics_status object indicating success or error
References helics_invalid_object, and helics_ok.
helicsFederateGetName()
HELICS_EXPORT helics_status helicsFederateGetName (helics_federate fed, char * outputString, int maxlen)
get the name of the federate
Parameters
fed the federate object to query
[out] outputString memory buffer to store the result
maxlen the maximum size of the buffer
Returns
helics_status object indicating success or error
References helics_discard, helics_invalid_object, and helics_ok.
helicsFederateGetState()
HELICS_EXPORT helics_status helicsFederateGetState (helics_federate fed, federate_state * state)
get the current state of a federate
Parameters
fed the fed to query
[out] state the resulting state if helics_status return helics_ok
References helics_discard, helics_invalid_object, and helics_ok.
helicsFederateInfoCreate()
HELICS_EXPORT helics_federate_info_t helicsFederateInfoCreate ()
create a federate info object for specifying federate information when constructing a federate
Returns
a helics_federate_info_t object which is a reference to the created object
helicsFederateInfoFree()
HELICS_EXPORT void helicsFederateInfoFree (helics_federate_info_t fi)
delete the memory associated with a federate info object
helicsFederateInfoLoadFromArgs()
HELICS_EXPORT helics_status helicsFederateInfoLoadFromArgs (helics_federate_info_t fi, int argc, const char *const * argv)
load a federate info from command line arguments
Parameters
fi a federateInfo object
argc the number of command line arguments
argv an array of strings from the command line
Returns
a helics_status enumeration indicating success or any potential errors
References helics_discard, helics_ok, and helics::FederateInfo::loadInfoFromArgs().
helicsFederateInfoSetCoreInitString()
HELICS_EXPORT helics_status helicsFederateInfoSetCoreInitString (helics_federate_info_t fi, const char * coreInit)
set the initialization string for the core usually in the form of command line arguments
Parameters
fi the federate info object to alter
coreInit a string with the core initialization strings
Returns
a helics_status enumeration helics_ok on success helicsInvalidReference if fi is not a valid reference
References helics::FederateInfo::coreInitString, helics_invalid_object, and helics_ok.
helicsFederateInfoSetCoreName()
HELICS_EXPORT helics_status helicsFederateInfoSetCoreName (helics_federate_info_t fi, const char * corename)
set the name of the core to link to for a federate
Parameters
fi the federate info object to alter
corename the identifier for a core to link to
Returns
a helics_status enumeration helics_ok on success helicsInvalidReference if fi is not a valid reference
References helics::FederateInfo::coreName, helics_invalid_object, and helics_ok.
helicsFederateInfoSetCoreType()
HELICS_EXPORT helics_status helicsFederateInfoSetCoreType (helics_federate_info_t fi, int coretype)
set the core type by integer code
valid values available by definitions in api-data.h
Parameters
fi the federate info object to alter
coretype an numerical code for a core type
Returns
a helics_status enumeration helics_ok on success helicsInvalidReference if fi is not a valid reference helics_discard if the string is not recognized
References helics::FederateInfo::coreType, helics_invalid_object, and helics_ok.
helicsFederateInfoSetCoreTypeFromString()
HELICS_EXPORT helics_status helicsFederateInfoSetCoreTypeFromString (helics_federate_info_t fi, const char * coretype)
set the core type from a string
Parameters
fi the federate info object to alter
coretype a string naming a core type
Returns
a helics_status enumeration helics_ok on success helicsInvalidReference if fi is not a valid reference helics_discard if the string is not recognized
References helics::FederateInfo::coreType, helics::coreTypeFromString(), helics::DEFAULT, helics_invalid_object, and helics_ok.
helicsFederateInfoSetFederateName()
HELICS_EXPORT helics_status helicsFederateInfoSetFederateName (helics_federate_info_t fi, const char * name)
set the federate name in the Federate Info structure
Parameters
fi the federate info object to alter
name the new identifier for the federate
Returns
a helics_status enumeration helics_ok on success
References helics_invalid_object, helics_ok, and helics::FederateInfo::name.
helicsFederateInfoSetFlag()
HELICS_EXPORT helics_status helicsFederateInfoSetFlag (helics_federate_info_t fi, int flag, helics_bool_t value)
set a flag in the info structure
valid flags are available flag-definitions.h
Parameters
fi the federate info object to alter
flag a numerical index for a flag
value the desired value of the flag helics_true or helics_false
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the coretype is not recognized
References helics_invalid_object, and OBSERVER_FLAG.
helicsFederateInfoSetInputDelay()
HELICS_EXPORT helics_status helicsFederateInfoSetInputDelay (helics_federate_info_t fi, helics_time_t inputDelay)
set the input delay for a federate info object
Parameters
fi the federate info object to alter
inputDelay the desired output delay of the federate
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified inputDelay is invalid
References helics_invalid_object.
helicsFederateInfoSetLoggingLevel()
HELICS_EXPORT helics_status helicsFederateInfoSetLoggingLevel (helics_federate_info_t fi, int logLevel)
set the logging level of a federate
<0 none, 0, errors only, 1+warnings, 2+summary, 3+debug, 4+trace
Parameters
fi the federateInfo object to alter
logLevel the specified log level for a federate
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference
References helics_invalid_object, helics_ok, and helics::CoreFederateInfo::logLevel.
helicsFederateInfoSetMaxIterations()
HELICS_EXPORT helics_status helicsFederateInfoSetMaxIterations (helics_federate_info_t fi, int maxIterations)
set the max iteration count to use in federate in the info object
a federate will iterate for at most min(maxIterations,core maxIterations)
Parameters
fi the federateInfo object to alter
maxIterations the maximum number of iterations a federate is allowed per timestep
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified offset is invalid
References helics_invalid_object, helics_ok, and helics::CoreFederateInfo::maxIterations.
helicsFederateInfoSetOutputDelay()
HELICS_EXPORT helics_status helicsFederateInfoSetOutputDelay (helics_federate_info_t fi, helics_time_t outputDelay)
set the output delay for a federate
Parameters
fi the federate info object to alter
outputDelay the desired output delay of the federate
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified outputdelay is invalid
References helics_invalid_object.
helicsFederateInfoSetPeriod()
HELICS_EXPORT helics_status helicsFederateInfoSetPeriod (helics_federate_info_t fi, helics_time_t period)
set the period for federate in the info object
a federate will grant time only on integer periods if the period is specified>0 the offset will shift this return by some amount of time such that the federate will only grant times such as period must be strictly greater than 0, though setting to 0 implies a period of the timeEpsilon used in HELICS
Parameters
fi the federateInfo object to alter
period the desired period
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified period is invalid
References helics_invalid_object.
helicsFederateInfoSetSeparator()
HELICS_EXPORT helics_status helicsFederateInfoSetSeparator (helics_federate_info_t fi, char separator)
set the separator charactor in the info structure
the separator character is the separation charactor for local publications/endpoints in creating their global name for example if the separator character is '/' then a local endpoint would have a globally reachable name of fedName/localName
Parameters
fi the federate info object to alter
separator the character to use as a separator
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the coretype is not recognized
References helics_invalid_object, helics_ok, and helics::FederateInfo::separator.
helicsFederateInfoSetTimeDelta()
HELICS_EXPORT helics_status helicsFederateInfoSetTimeDelta (helics_federate_info_t fi, helics_time_t timeDelta)
set the minimum time delta between returns for a federate info object
Parameters
fi the federate info object to alter
timeDelta the desired output delay of the federate
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified time_delta is invalid
References helics_invalid_object.
helicsFederateInfoSetTimeOffset()
HELICS_EXPORT helics_status helicsFederateInfoSetTimeOffset (helics_federate_info_t fi, helics_time_t timeOffset)
set the time offset for federate in the info object
a federate will grant time only on integer periods if the period is specified>0 the offset will shift this return by some amount of time such that the federate will only grant times such as
Parameters
fi the federateInfo object to alter
timeOffset the desired timeOffset
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the specified offset is invalid
References helics_invalid_object, helics_ok, and helics::CoreFederateInfo::offset.
helicsFederateIsAsyncOperationCompleted()
HELICS_EXPORT helics_bool_t helicsFederateIsAsyncOperationCompleted (helics_federate fed)
check if the current Asynchronous operation has completed
Parameters
fed the federate to operate on
Returns
0 if not completed, 1 if completed
helicsFederateRequestTime()
HELICS_EXPORT helics_status helicsFederateRequestTime (helics_federate fed, helics_time_t requestTime, helics_time_t * timeOut)
request the next time for federate execution
Parameters
fed the federate to make the request of
requestTime the next requested time
[out] timeOut the time granted to the federate
Returns
a helics_status if the return value is equal to helics_ok the timeOut will contain the new granted time, otherwise timeOut is invalid
References helics_invalid_object, and helics_ok.
helicsFederateRequestTimeAsync()
HELICS_EXPORT helics_status helicsFederateRequestTimeAsync (helics_federate fed, helics_time_t requestTime)
request the next time for federate execution in an asynchronous call
call /ref helicsFederateRequestTimeComplete to finish the call
Parameters
fed the federate to make the request of
requestTime the next requested time
Returns
a helics_status if the return value is equal to helics_ok
References helics_invalid_object, and helics_ok.
helicsFederateRequestTimeComplete()
HELICS_EXPORT helics_status helicsFederateRequestTimeComplete (helics_federate fed, helics_time_t * timeOut)
complete an asynchronous requestTime call
Parameters
fed the federate to make the request of
[out] timeOut the time granted to the federate
Returns
a helics_status if the return value is equal to helics_ok the timeOut will contain the new granted time, otherwise timeOut is invalid
References helics_invalid_object, and helics_ok.
helicsFederateRequestTimeIterative()
HELICS_EXPORT helics_status helicsFederateRequestTimeIterative (helics_federate fed, helics_time_t requestTime, helics_iteration_request iterate, helics_time_t * timeOut, helics_iteration_status * outIterate)
request an iterative time
this call allows for finer grain control of the iterative process then /ref helicsFederateRequestTime it takes a time and and iteration request and return a time and iteration status
Parameters
fed the federate to make the request of
requestTime the next desired time
iterate the requested iteration mode
[out] timeOut the granted time
[out] outIterate the iteration specification of the result
Returns
a helics_status object with a return code of the result
References helics::error, helics_error, helics_invalid_object, and helics_ok.
helicsFederateRequestTimeIterativeAsync()
HELICS_EXPORT helics_status helicsFederateRequestTimeIterativeAsync (helics_federate fed, helics_time_t requestTime, helics_iteration_request iterate)
request an iterative time through an asynchronous call
this call allows for finer grain control of the iterative process then /ref helicsFederateRequestTime it takes a time and and iteration request and return a time and iteration status call /ref helicsFederateRequestTimeIterativeComplete to finish the process
Parameters
fed the federate to make the request of
requestTime the next desired time
iterate the requested iteration mode
Returns
a helics_status object with a return code of the result
References helics_invalid_object, and helics_ok.
helicsFederateRequestTimeIterativeComplete()
HELICS_EXPORT helics_status helicsFederateRequestTimeIterativeComplete (helics_federate fed, helics_time_t * timeOut, helics_iteration_status * outIterate)
complete an iterative time request asynchronous call
Parameters
fed the federate to make the request of
[out] timeOut the granted time
[out] outIterate the iteration specification of the result
Returns
a helics_status object with a return code of the result
References helics::error, helics_error, helics_invalid_object, and helics_ok.
helicsFederateSetFlag()
HELICS_EXPORT helics_status helicsFederateSetFlag (helics_federate fed, int flag, helics_bool_t flagValue)
set a flag for the federate
Parameters
fed the federate to alter a flag for
flag the flag to change
flagValue the new value of the flag 0 for false !=0 for true
References helics_invalid_object.
helicsFederateSetInputDelay()
HELICS_EXPORT helics_status helicsFederateSetInputDelay (helics_federate fed, helics_time_t inputDelay)
set the impact Window time
the impact window is the time window around the time request in which other federates cannot affect the federate
Parameters
[in] lookAhead the look ahead time
References helics_invalid_object, and helics_ok.
helicsFederateSetLoggingLevel()
HELICS_EXPORT helics_status helicsFederateSetLoggingLevel (helics_federate fed, int loggingLevel)
set the logging level for the federate @ details debug and trace only do anything if they were enabled in the compilation
Parameters
loggingLevel (-1: none, 0: error_only, 1: warnings, 2: normal, 3: debug, 4: trace)
References helics_invalid_object, and helics_ok.
helicsFederateSetMaxIterations()
HELICS_EXPORT helics_status helicsFederateSetMaxIterations (helics_federate fi, int maxIterations)
set the max iteration count to use in federate in the info object
a federate will iterate for at most min(maxIterations,core maxIterations)
Parameters
fi the federateInfo object to alter
maxIterations the maximum number of iterations a federate is allowed per timestep
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fed is not a valid reference helics_discard if the specified offset is invalid
References helics_invalid_object, and helics_ok.
helicsFederateSetOutputDelay()
HELICS_EXPORT helics_status helicsFederateSetOutputDelay (helics_federate fed, helics_time_t outputDelay)
set the look ahead time
the look ahead is the propagation time for messages/event to propagate from the Federate the federate
Parameters
[in] lookAhead the look ahead time
References helics_invalid_object, and helics_ok.
helicsFederateSetPeriod()
HELICS_EXPORT helics_status helicsFederateSetPeriod (helics_federate fed, helics_time_t period, helics_time_t offset)
set the period and offset of the federate
the federate will on grant time on N*period+offset interval
Parameters
[in] period the length of time between each subsequent grants
[in] offset the shift of the period from 0 offset must be < period
References helics_invalid_object, and helics_ok.
helicsFederateSetSeparator()
HELICS_EXPORT helics_status helicsFederateSetSeparator (helics_federate fed, char separator)
set the separator charactor in the info structure
the separator character is the separation charactor for local publications/endpoints in creating their global name for example if the separator character is '/' then a local endpoint would have a globally reachable name of fedName/localName
Parameters
fi the federate info object to alter
separator the character to use as a separator
Returns
a helics_status enumeration helics_ok on success helics_invalid_object if fi is not a valid reference helics_discard if the coretype is not recognized
References helics_invalid_object, and helics_ok.
helicsFederateSetTimeDelta()
HELICS_EXPORT helics_status helicsFederateSetTimeDelta (helics_federate fed, helics_time_t time)
set the minimum time delta for the federate
Parameters
[in] tdelta the minimum time delta to return from a time request function
References helics_invalid_object, and helics_ok.
helicsGetFederateByName()
HELICS_EXPORT helics_federate helicsGetFederateByName (const char * fedName)
get an existing federate object from a core by name
the federate must have been created by one of the other functions and at least one of the objects referencing the created federate must still be active in the process
Parameters
fedName the name of the federate to retrieve
Returns
NULL if no fed is available by that name otherwise a helics_federate with that name
References helicsFederateClone().
helicsGetVersion()
HELICS_EXPORT const char* helicsGetVersion ()
get a version string for HELICS
References helics::versionString.
Referenced by helics::getHelicsVersionString().
helicsIsCoreTypeAvailable()
HELICS_EXPORT helics_bool_t helicsIsCoreTypeAvailable (const char * type)
Returns true if core/broker type specified is available in current compilation.
possible options include "test","zmq","udp","ipc","interprocess","tcp","default", "mpi"
helicsQueryBrokerExecute()
HELICS_EXPORT const char* helicsQueryBrokerExecute (helics_query query, helics_broker broker)
Execute a query directly on a broker
the call will block until the query finishes which may require communication or other delays
Parameters
query the query object to use in the query
broker the broker to send the query to
Returns
a pointer to a string. the string will remain valid until the query is freed or executed again the return will be nullptr if fed or query is an invalid object, the return string will be "#invalid" if the query itself was invalid
References helics::queryObject::response.
helicsQueryCoreExecute()
HELICS_EXPORT const char* helicsQueryCoreExecute (helics_query query, helics_core core)
Execute a query directly on a core
the call will block until the query finishes which may require communication or other delays
Parameters
query the query object to use in the query
core the core to send the query to
Returns
a pointer to a string. the string will remain valid until the query is freed or executed again the return will be nullptr if fed or query is an invalid object, the return string will be "#invalid" if the query itself was invalid
References helics::queryObject::response.
helicsQueryExecute()
HELICS_EXPORT const char* helicsQueryExecute (helics_query query, helics_federate fed)
Execute a query
the call will block until the query finishes which may require communication or other delays
Parameters
query the query object to use in the query
fed a federate to send the query through
Returns
a pointer to a string. the string will remain valid until the query is freed or executed again the return will be nullptr if fed or query is an invalid object, the return string will be "#invalid" if the query itself was invalid
References helics::queryObject::response.
Referenced by helics::Federate::query().
helicsQueryExecuteAsync()
HELICS_EXPORT helics_status helicsQueryExecuteAsync (helics_query query, helics_federate fed)
Execute a query in a non-blocking call
Parameters
query the query object to use in the query
fed a federate to send the query through
Returns
a helics status enumeration with the result of the query specification
References helics::queryObject::asyncIndexCode, helics_invalid_object, and helics_ok.
helicsQueryExecuteComplete()
HELICS_EXPORT const char* helicsQueryExecuteComplete (helics_query query)
complete the return from a query called with /ref helicsExecuteQueryAsync
the function will block until the query completes /ref isQueryComplete can be called to determine if a query has completed or not
Parameters
query the query object to
Returns
a pointer to a string. the string will remain valid until the query is freed or executed again the return will be nullptr if query is an invalid object
References helics::invalid_id_value, and helics::queryObject::response.
helicsQueryFree()
HELICS_EXPORT void helicsQueryFree (helics_query)
free the memory associated with a query object
Referenced by helics::Federate::query().
helicsQueryIsCompleted()
HELICS_EXPORT helics_bool_t helicsQueryIsCompleted (helics_query query)
check if an asynchronously executed query has completed
Returns
will return helics_true if an asynchronous query has complete or a regular query call was made with a result and false if an asynchronous query has not completed or is invalid