helics: ValueFederate.h File Reference
ValueFederate.h File Reference
The C-API function for valueFederates.
#include "helics.h"
Macros
#define HELICS_DATA_TYPE_STRING 0
#define HELICS_DATA_TYPE_DOUBLE 1
#define HELICS_DATA_TYPE_INT 2
#define HELICS_DATA_TYPE_COMPLEX 3
#define HELICS_DATA_TYPE_VECTOR 4
#define HELICS_DATA_TYPE_NAMEDPOINT 6
#define HELICS_DATA_TYPE_BOOLEAN 7
#define HELICS_DATA_TYPE_RAW 25
Functions
HELICS_EXPORT helics_subscription helicsFederateRegisterSubscription (helics_federate fed, const char *key, const char *type, const char *units)
HELICS_EXPORT helics_subscription helicsFederateRegisterTypeSubscription (helics_federate fed, const char *key, int type, const char *units)
HELICS_EXPORT helics_subscription helicsFederateRegisterOptionalSubscription (helics_federate fed, const char *key, const char *type, const char *units)
HELICS_EXPORT helics_subscription helicsFederateRegisterOptionalTypeSubscription (helics_federate fed, const char *key, int type, const char *units)
HELICS_EXPORT helics_publication helicsFederateRegisterPublication (helics_federate fed, const char *key, const char *type, const char *units)
HELICS_EXPORT helics_publication helicsFederateRegisterTypePublication (helics_federate fed, const char *key, int type, const char *units)
HELICS_EXPORT helics_publication helicsFederateRegisterGlobalPublication (helics_federate fed, const char *key, const char *type, const char *units)
HELICS_EXPORT helics_publication helicsFederateRegisterGlobalTypePublication (helics_federate fed, const char *key, int type, const char *units)
HELICS_EXPORT helics_status helicsPublicationPublishRaw (helics_publication pub, const void *data, int inputDataLength)
HELICS_EXPORT helics_status helicsPublicationPublishString (helics_publication pub, const char *str)
HELICS_EXPORT helics_status helicsPublicationPublishInteger (helics_publication pub, int64_t val)
HELICS_EXPORT helics_status helicsPublicationPublishBoolean (helics_publication pub, helics_bool_t val)
HELICS_EXPORT helics_status helicsPublicationPublishDouble (helics_publication pub, double val)
HELICS_EXPORT helics_status helicsPublicationPublishComplex (helics_publication pub, double real, double imag)
HELICS_EXPORT helics_status helicsPublicationPublishVector (helics_publication pub, const double *vectorInput, int vectorlength)
HELICS_EXPORT helics_status helicsPublicationPublishNamedPoint (helics_publication pub, const char *str, double val)
HELICS_EXPORT int helicsSubscriptionGetValueSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetRawValue (helics_subscription sub, void *data, int maxlen, int *actualLength)
HELICS_EXPORT int helicsSubscriptionGetStringSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetString (helics_subscription sub, char *outputString, int maxStringlen, int *actualLength)
HELICS_EXPORT helics_status helicsSubscriptionGetInteger (helics_subscription sub, int64_t *val)
HELICS_EXPORT helics_status helicsSubscriptionGetBoolean (helics_subscription sub, helics_bool_t *val)
HELICS_EXPORT helics_status helicsSubscriptionGetDouble (helics_subscription sub, double *val)
HELICS_EXPORT helics_status helicsSubscriptionGetComplex (helics_subscription sub, double *real, double *imag)
HELICS_EXPORT int helicsSubscriptionGetVectorSize (helics_subscription sub)
HELICS_EXPORT helics_status helicsSubscriptionGetVector (helics_subscription sub, double data[], int maxlen, int *actualSize)
HELICS_EXPORT helics_status helicsSubscriptionGetNamedPoint (helics_subscription sub, char *outputString, int maxStringlen, int *actualLength, double *val)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultRaw (helics_subscription sub, const void *data, int inputDataLength)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultString (helics_subscription sub, const char *str)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultInteger (helics_subscription sub, int64_t val)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultBoolean (helics_subscription sub, helics_bool_t val)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultDouble (helics_subscription sub, double val)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultComplex (helics_subscription sub, double real, double imag)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultVector (helics_subscription sub, const double *vectorInput, int vectorlength)
HELICS_EXPORT helics_status helicsSubscriptionSetDefaultNamedPoint (helics_subscription sub, const char *str, double val)
HELICS_EXPORT helics_status helicsSubscriptionGetType (helics_subscription sub, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsPublicationGetType (helics_publication pub, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsSubscriptionGetKey (helics_subscription sub, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsPublicationGetKey (helics_publication pub, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsSubscriptionGetUnits (helics_subscription sub, char *outputString, int maxlen)
HELICS_EXPORT helics_status helicsPublicationGetUnits (helics_publication pub, char *outputString, int maxlen)
HELICS_EXPORT helics_bool_t helicsSubscriptionIsUpdated (helics_subscription sub)
HELICS_EXPORT helics_time_t helicsSubscriptionLastUpdateTime (helics_subscription sub)
HELICS_EXPORT int helicsFederateGetPublicationCount (helics_federate fed)
HELICS_EXPORT int helicsFederateGetSubscriptionCount (helics_federate fed)
Detailed Description
The C-API function for valueFederates.
Macro Definition Documentation
HELICS_DATA_TYPE_BOOLEAN
#define HELICS_DATA_TYPE_BOOLEAN 7
a boolean data type
Referenced by helicsFederateRegisterGlobalTypePublication(), helicsFederateRegisterOptionalTypeSubscription(), helicsFederateRegisterTypePublication(), and helicsFederateRegisterTypeSubscription().
HELICS_DATA_TYPE_COMPLEX
#define HELICS_DATA_TYPE_COMPLEX 3
a pair of doubles representing a complex number
HELICS_DATA_TYPE_DOUBLE
#define HELICS_DATA_TYPE_DOUBLE 1
a double precision floating point number
HELICS_DATA_TYPE_INT
#define HELICS_DATA_TYPE_INT 2
a 64 bit integer
HELICS_DATA_TYPE_NAMEDPOINT
#define HELICS_DATA_TYPE_NAMEDPOINT 6
a named point consisting of a string and a double
HELICS_DATA_TYPE_RAW
#define HELICS_DATA_TYPE_RAW 25
raw data type
Referenced by helicsFederateRegisterGlobalTypePublication(), helicsFederateRegisterOptionalTypeSubscription(), helicsFederateRegisterTypePublication(), and helicsFederateRegisterTypeSubscription().
HELICS_DATA_TYPE_STRING
#define HELICS_DATA_TYPE_STRING 0
a sequence of characters
HELICS_DATA_TYPE_VECTOR
#define HELICS_DATA_TYPE_VECTOR 4
an array of doubles
Function Documentation
helicsFederateGetPublicationCount()
HELICS_EXPORT int helicsFederateGetPublicationCount (helics_federate fed)
get the number of publications in a federate
Returns
(-1) if fed was not a valid federate otherwise returns the number of publications
helicsFederateGetSubscriptionCount()
HELICS_EXPORT int helicsFederateGetSubscriptionCount (helics_federate fed)
get the number of subscriptions in a federate
Returns
(-1) if fed was not a valid federate otherwise returns the number of subscriptions
helicsFederateRegisterGlobalPublication()
HELICS_EXPORT helics_publication helicsFederateRegisterGlobalPublication (helics_federate fed, const char * key, const char * type, const char * units)
register a global named publication with an arbitrary type
the publication becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a publication
key the identifier for the publication
type a string describing the expected type of the publication
units a string listing the units of the subscription maybe NULL
Returns
an object containing the publication
References helics::getTypeFromString().
Referenced by helicsFederateRegisterGlobalTypePublication().
helicsFederateRegisterGlobalTypePublication()
HELICS_EXPORT helics_publication helicsFederateRegisterGlobalTypePublication (helics_federate fed, const char * key, int type, const char * units)
register a global publication with a defined type
the publication becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a publication
key the identifier for the publication
type a code identifying the type of the publication one of HELICS_DATA_TYPE_STRING, HELICS_DATA_TYPE_INT, HELICS_DATA_TYPE_DOUBLE, HELICS_DATA_TYPE_COMPLEX, HELICS_DATA_TYPE_VECTOR, HELICS_DATA_TYPE_NAMEDPOINT, HELICS_DATA_TYPE_BOOLEAN HELICS_DATA_TYPE_RAW
units a string listing the units of the subscription maybe NULL
Returns
an object containing the publication
References HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_RAW, and helicsFederateRegisterGlobalPublication().
helicsFederateRegisterOptionalSubscription()
HELICS_EXPORT helics_subscription helicsFederateRegisterOptionalSubscription (helics_federate fed, const char * key, const char * type, const char * units)
create a subscription that is specifically stated to be optional
the subscription becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
optional implies that there may or may not be matching publication elsewhere in the federation
Parameters
fed the federate object in which to create a subscription
key the identifier matching a publication to get a subscription for
type a string describing the expected type of the publication may be NULL
units a string listing the units of the subscription maybe NULL
Returns
an object containing the subscription
References helics::getTypeFromString().
Referenced by helicsFederateRegisterOptionalTypeSubscription(), and helics::ValueFederate::registerOptionalSubscription().
helicsFederateRegisterOptionalTypeSubscription()
HELICS_EXPORT helics_subscription helicsFederateRegisterOptionalTypeSubscription (helics_federate fed, const char * key, int type, const char * units)
create a subscription of a specific known type that is specifically stated to be optional
the subscription becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications optional implies that there may or may not be matching publication elsewhere in the federation
Parameters
fed the federate object in which to create a subscription
key the identifier matching a publication to get a subscription for
type a known type identifier HELICS_DATA_TYPE_STRING, HELICS_DATA_TYPE_INT, HELICS_DATA_TYPE_DOUBLE, HELICS_DATA_TYPE_COMPLEX, HELICS_DATA_TYPE_VECTOR, HELICS_DATA_TYPE_NAMEDPOINT, HELICS_DATA_TYPE_BOOLEAN HELICS_DATA_TYPE_RAW
units a string listing the units of the subscription maybe NULL
Returns
an object containing the subscription
References HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_RAW, and helicsFederateRegisterOptionalSubscription().
helicsFederateRegisterPublication()
HELICS_EXPORT helics_publication helicsFederateRegisterPublication (helics_federate fed, const char * key, const char * type, const char * units)
register a publication with an arbitrary type
the publication becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a publication
key the identifier for the publication the global publication key will be prepended with the federate name
type a string describing the expected type of the publication
units a string listing the units of the subscription maybe NULL
Returns
an object containing the publication
References helics::getTypeFromString().
Referenced by helicsFederateRegisterTypePublication(), and helics::ValueFederate::registerPublication().
helicsFederateRegisterSubscription()
HELICS_EXPORT helics_subscription helicsFederateRegisterSubscription (helics_federate fed, const char * key, const char * type, const char * units)
create a subscription
the subscription becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a subscription must have been create with helicsCreateValueFederate or helicsCreateCombinationFederate
key the identifier matching a publication to get a subscription for
type a string describing the expected type of the publication may be NULL
units a string listing the units of the subscription maybe NULL
Returns
an object containing the subscription
References helics::getTypeFromString().
Referenced by helicsFederateRegisterTypeSubscription(), and helics::ValueFederate::registerSubscription().
helicsFederateRegisterTypePublication()
HELICS_EXPORT helics_publication helicsFederateRegisterTypePublication (helics_federate fed, const char * key, int type, const char * units)
register a publication with a defined type
the publication becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a publication
key the identifier for the publication
type a code identifying the type of the publication one of HELICS_DATA_TYPE_STRING, HELICS_DATA_TYPE_INT, HELICS_DATA_TYPE_DOUBLE, HELICS_DATA_TYPE_COMPLEX, HELICS_DATA_TYPE_VECTOR, HELICS_DATA_TYPE_NAMEDPOINT, HELICS_DATA_TYPE_BOOLEAN HELICS_DATA_TYPE_RAW
units a string listing the units of the subscription maybe NULL
Returns
an object containing the publication
References HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_RAW, and helicsFederateRegisterPublication().
helicsFederateRegisterTypeSubscription()
HELICS_EXPORT helics_subscription helicsFederateRegisterTypeSubscription (helics_federate fed, const char * key, int type, const char * units)
create a subscription of a specific known type
the subscription becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for subscriptions and publications
Parameters
fed the federate object in which to create a subscription
key the identifier matching a publication to get a subscription for
type a known type identifier HELICS_DATA_TYPE_STRING, HELICS_DATA_TYPE_INT, HELICS_DATA_TYPE_DOUBLE, HELICS_DATA_TYPE_COMPLEX, HELICS_DATA_TYPE_VECTOR, HELICS_DATA_TYPE_NAMEDPOINT, HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_RAW
units a string listing the units of the subscription maybe NULL
Returns
an object containing the subscription
References HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_RAW, and helicsFederateRegisterSubscription().
helicsSubscriptionIsUpdated()
HELICS_EXPORT helics_bool_t helicsSubscriptionIsUpdated (helics_subscription sub)
check if a particular subscription was updated
Returns
true if it has been updated since the last value retrieval
Referenced by helics::Subscription::isUpdated().
helicsSubscriptionLastUpdateTime()
HELICS_EXPORT helics_time_t helicsSubscriptionLastUpdateTime (helics_subscription sub)
get the last time a subscription was updated
Referenced by helics::Subscription::getLastUpdateTime().